### PR TITLE
Refactored config handling

### PR DESCRIPTION
**Pull request by phipleg**
Instead of passing command line parameters (--host, --port, --base,
--db_path) one just passes a single command --config my_config.yml.
See etc/example_config.yml for an example configuration.

The config will be parsed as a dict and is globally available as
`bbtornado.config`.

### CODE REVIEW

**Comment by gromgull** [comment]
this looks good! But readability is important! Make the config object a Tornado ObjectDict (http://www.tornadoweb.org/en/stable/util.html#tornado.util.ObjectDict), then you can access things as attributes. 

And bumb the version number!

**Comment by phipleg** [comment]
What version number should it be? It is not totally backwards compatible because it doesn't access a `settings` object anymore, so we should increase the major number: What about `1.0.0` ?

**Comment by gromgull** [comment]
Thanks for the ObjectDict!

1.0.0 feels so grown up :D 

But yeah, it does need to bump the major version if we want to pretend to do semver. 

Make it so!

**Comment by phipleg** [comment]
Done!

**Pull request merged**
